#pragma once

#include <JuceHeader.h>

/**
    Seconda tabella di help, piu' ampia ma "piu' leggera" di
    CsoundOpcodeHelpData::table: una riga di descrizione per opcode,
    trascritta dalla riga "refpurpose" del Csound Reference Manual
    (csound.com/docs/manual/PartReference.html, l'indice alfabetico
    completo di opcode e operatori - lo stesso testo che CsoundQt mostra
    come help rapido, preso dal manuale che lui ha in locale).

    A differenza di CsoundOpcodeHelpData::table (sintassi completa + prosa,
    verificata pagina per pagina, ma solo per gli opcode piu' comuni), qui
    non c'e' la riga di sintassi "umana" - quella, per questi opcode, resta
    la firma di tipo grezza letta dal motore (vedi
    CsoundCodeEditor::pushSignatureHelp). Questa tabella copre solo gli
    operatori/simboli e gli opcode le cui iniziali vanno dai simboli fino
    alla lettera L compresa (il fetch in blocco dell'indice del manuale si
    interrompe per limite di dimensione intorno alla lettera O, ma per
    restare su descrizioni rilette e controllate ci si e' fermati a L);
    sono stati esclusi di proposito i gruppi di opcode molto di nicchia
    (widget FLTK "FL*", integrazione Jack "Jacko*"/"jacktransport",
    analisi/risintesi ATS "ATS*", Ableton Link "link_*", lettura/scrittura
    HDF5, orchestra remota "insremot"/"insglobal", gestione immagini
    "image*") perche' sono centinaia di opcode molto specialistici che
    raramente si digitano esplorando l'autocompletamento. Per TUTTI gli
    opcode non presenti ne' qui ne' in CsoundOpcodeHelpData, l'help mostra
    comunque la firma di tipo grezza (sempre corretta, letta dal motore),
    semplicemente senza una riga di descrizione in prosa - ampliare questa
    tabella (o quella in CsoundOpcodeHelpData) resta il modo naturale per
    aggiungere altre descrizioni in futuro.
*/
struct CsoundOpcodePurpose
{
    const char* name;
    const char* purpose;
};

namespace CsoundOpcodePurposeDataNS
{
    static const CsoundOpcodePurpose table[] =
    {
        { "!=", "Determines if one value is not equal to another." },
        { "#define", "Defines a macro." },
        { "#include", "Includes an external file for processing." },
        { "#undef", "Un-defines a macro." },
        { "#ifdef", "Conditional reading of code." },
        { "#ifndef", "Conditional reading of code." },
        { "$NAME", "Calls a defined macro." },
        { "%", "Modulus operator." },
        { "&&", "Logical AND operator." },
        { ">", "Determines if one value is greater than another." },
        { ">=", "Determines if one value is greater than or equal to another." },
        { "<", "Determines if one value is less than another." },
        { "<=", "Determines if one value is less than or equal to another." },
        { "*", "Multiplication operator." },
        { "+", "Addition operator." },
        { "-", "Subtraction operator." },
        { "/", "Division operator." },
        { "=", "Performs a simple assignment." },
        { "+=", "Performs add and assignment." },
        { "==", "Compares two values for equality." },
        { "^", "\"Power of\" operator." },
        { "||", "Logical OR operator." },
        { "!", "Logical NOT operator." },
        { "0dbfs", "Sets the value of 0 decibels using full scale amplitude." },
        { "A4", "Sets the base frequency for pitch A4." },
        { "<<", "Bitshift left operator." },
        { ">>", "Bitshift right operator." },
        { "&", "Bitwise AND operator." },
        { "|", "Bitwise OR operator." },
        { "#", "Bitwise NON EQUIVALENCE operator." },
        { "a", "Converts a k-rate parameter to an a-rate value with interpolation." },
        { "abs", "Returns an absolute value." },
        { "active", "Returns the number of active instances of an instrument." },
        { "adsr", "Calculates the classical ADSR envelope using linear segments." },
        { "adsyn", "Output is an additive set of individually controlled sinusoids, using an oscillator bank." },
        { "adsynt", "Performs additive synthesis with an arbitrary number of partials, not necessarily harmonic." },
        { "adsynt2", "Additive synthesis with an arbitrary number of (not necessarily harmonic) partials, with interpolation." },
        { "aftouch", "Get the current after-touch value for this channel." },
        { "allpole", "Allpole filter implementation using direct convolution." },
        { "alpass", "Reverberates an input signal with a flat frequency response." },
        { "alwayson", "Activates the indicated instrument in the orchestra header, without needing an i statement." },
        { "ampdb", "Returns the amplitude equivalent of a decibel value." },
        { "ampdbfs", "Returns the amplitude equivalent (16-bit signed integer scale) of a full scale decibel (dB FS) value." },
        { "ampmidicurve", "Maps an input MIDI velocity number to an output gain factor with a maximum value of 1." },
        { "ampmidid", "Musically maps MIDI velocity to peak amplitude within a specified dynamic range in decibels." },
        { "apoleparams", "Extracts allpole filter parameters from coefficients." },
        { "areson", "A notch filter whose transfer functions are the complements of the reson opcode." },
        { "aresonk", "A notch filter whose transfer functions are the complements of the reson opcode (k-rate)." },
        { "atone", "A hi-pass filter whose transfer functions are the complements of the tone opcode." },
        { "atonek", "A hi-pass filter whose transfer functions are the complements of the tonek opcode." },
        { "atonex", "Emulates a stack of filters using the atone opcode." },
        { "autocorr", "Autocorrelation of a sequence." },
        { "babo", "A physical model reverberator." },
        { "balance", "Adjusts one audio signal according to the values of another." },
        { "balance2", "Adjusts one audio signal according to the values of another." },
        { "bamboo", "Semi-physical model of a bamboo sound." },
        { "barmodel", "Creates a tone similar to a struck metal bar." },
        { "bbcutm", "Generates breakbeat-style cut-ups of a mono audio stream." },
        { "bbcuts", "Generates breakbeat-style cut-ups of a stereo audio stream." },
        { "betarand", "Beta distribution random number generator (positive values only)." },
        { "bexprnd", "Exponential distribution random number generator." },
        { "bformenc1", "Codes a signal into the ambisonic B format." },
        { "bformdec1", "Decodes an ambisonic B format signal." },
        { "bformdec2", "Decodes an Ambisonics B format signal." },
        { "binit", "PVS tracks to amplitude+frequency conversion." },
        { "biquad", "A sweepable general purpose biquadratic digital filter." },
        { "biquada", "A sweepable general purpose biquadratic digital filter with a-rate parameters." },
        { "birnd", "Returns a random number in a bi-polar range." },
        { "bob", "Runge-Kutte numerical simulation of the Moog analog resonant filter." },
        { "bpf", "Break point function with linear interpolation." },
        { "bpfcos", "Break point function with cosine (ease-in/ease-out) interpolation." },
        { "bqrez", "A second-order multi-mode filter." },
        { "butbp", "Same as the butterbp opcode." },
        { "butbr", "Same as the butterbr opcode." },
        { "buthp", "Same as the butterhp opcode." },
        { "butlp", "Same as the butterlp opcode." },
        { "butterbp", "A band-pass Butterworth filter." },
        { "butterbr", "A band-reject Butterworth filter." },
        { "butterhp", "A high-pass Butterworth filter." },
        { "butterlp", "A low-pass Butterworth filter." },
        { "button", "Sense on-screen controls." },
        { "buzz", "Output is a set of harmonically related sine partials." },
        { "c2r", "Real to complex format conversion." },
        { "cabasa", "Semi-physical model of a cabasa sound." },
        { "cauchy", "Cauchy distribution random number generator." },
        { "cauchyi", "Cauchy distribution random number generator with interpolation." },
        { "ceil", "Returns the smallest integer not less than x." },
        { "cell", "Cellular Automaton." },
        { "cent", "Calculates a factor to raise/lower a frequency by a given amount of cents." },
        { "centroid", "Calculates the spectral centroid of a signal." },
        { "ceps", "Calculates the cepstrum of an array input, optionally filtering coefficients." },
        { "cepsinv", "Calculates the inverse cepstrum of an array." },
        { "cggoto", "Conditionally transfer control on every pass." },
        { "chanctrl", "Get the current value of a MIDI channel controller." },
        { "changed", "k-rate signal change detector." },
        { "changed2", "k-rate signal change detector (multiple inputs)." },
        { "chani", "Reads data from the software bus." },
        { "chano", "Sends data to the outwards software bus." },
        { "cbrt", "Cubic root function." },
        { "chebyshevpoly", "Efficiently evaluates the sum of Chebyshev polynomials of arbitrary order." },
        { "checkbox", "Sense on-screen controls." },
        { "chn", "Declares a channel of the named software bus." },
        { "chnclear", "Clears a number of audio output channels of the named software bus." },
        { "chnexport", "Exports a global variable as a channel of the software bus." },
        { "chnmix", "Writes audio data to the named software bus, mixing with the previous output." },
        { "chnparams", "Queries parameters of a software bus channel." },
        { "chuap", "Simulates Chua's oscillator, an LRC oscillator capable of bifurcation and chaotic attractors." },
        { "cigoto", "Conditionally transfer control during the i-time pass." },
        { "ckgoto", "Conditionally transfer control during the performance-time passes." },
        { "clear", "Zeroes a list of audio signals." },
        { "clfilt", "Implements low-pass and high-pass filters of different styles." },
        { "clip", "Clips a signal to a predefined limit." },
        { "clockoff", "Stops one of a number of internal clocks." },
        { "clockon", "Starts one of a number of internal clocks." },
        { "cmp", "Compares audio signals or arrays." },
        { "cmplxprod", "Complex product of two arrays." },
        { "cngoto", "Transfers control on every pass when a condition is not true." },
        { "comb", "Reverberates an input signal with a \"colored\" frequency response." },
        { "combinv", "Reverberates an input signal with a \"colored\" frequency response (inverted)." },
        { "compilecsd", "Compiles a new orchestra from an ASCII file." },
        { "compileorc", "Compiles a new orchestra from an ASCII file." },
        { "compilestr", "Compiles a new orchestra passed in as an ASCII string." },
        { "compress", "Compresses, limits, expands, ducks or gates an audio signal." },
        { "compress2", "Compresses, limits, expands, ducks or gates an audio signal." },
        { "connect", "Connects a source outlet to a sink inlet." },
        { "control", "Configurable slider controls for realtime user input." },
        { "convle", "Same as the convolve opcode." },
        { "convolve", "Convolves a signal and an impulse response." },
        { "copya2ftab", "Copies data from a vector to an f-table." },
        { "copyf2array", "Copies data from an f-table to a vector." },
        { "cos", "Performs a cosine function." },
        { "cosseg", "Traces a series of line segments between specified points with cosine interpolation." },
        { "cossegb", "Traces a series of line segments between specified absolute points with cosine interpolation." },
        { "cossegr", "Cosine-interpolated line segments, including a release segment." },
        { "cosh", "Performs a hyperbolic cosine function." },
        { "cosinv", "Performs an arccosine function." },
        { "count", "Gets the next value from a counter." },
        { "count_i", "Gets the next value from a counter (init-time)." },
        { "cntCycles", "Gets the number of times a counter has cycled." },
        { "cntRead", "Reads the current value of a counter object." },
        { "cntReset", "Resets a counter object." },
        { "cntState", "Gives the range and increment of a counter." },
        { "cntCreate", "Creates a counter object." },
        { "cntDelete", "Deletes a counter." },
        { "cntDelete_i", "Deletes a counter (init-time)." },
        { "cps2pch", "Converts a pitch-class value into cycles-per-second for equal divisions of the octave." },
        { "cpsmidib", "Note number of the current MIDI event, modified by pitch-bend, expressed in cycles-per-second." },
        { "cpsmidinn", "Converts a MIDI note number value to cycles-per-second." },
        { "cpsoct", "Converts an octave-point-decimal value to cycles-per-second." },
        { "cpspch", "Converts a pitch-class value to cycles-per-second." },
        { "cpstmid", "Gets a MIDI note number (allows customized micro-tuning scales)." },
        { "cpstun", "Returns micro-tuning values at k-rate." },
        { "cpstuni", "Returns micro-tuning values at init-rate." },
        { "cpsxpch", "Converts a pitch-class value into cycles-per-second for equal divisions of any interval." },
        { "cpumeter", "Reports CPU usage, either total or per core." },
        { "cpuprc", "Controls allocation of CPU resources on a per-instrument basis, to optimize realtime output." },
        { "cross2", "Cross synthesis using FFTs." },
        { "crossfm", "Two mutually frequency and/or phase modulated oscillators." },
        { "crunch", "Semi-physical model of a crunch sound." },
        { "ctrl14", "A floating-point 14-bit MIDI signal scaled with a minimum and a maximum range." },
        { "ctrl21", "A floating-point 21-bit MIDI signal scaled with a minimum and a maximum range." },
        { "ctrl7", "A floating-point 7-bit MIDI signal scaled with a minimum and a maximum range." },
        { "ctrlinit", "Sets the initial values for a set of MIDI controllers." },
        { "ctrlpreset", "Defines a preset for MIDI controllers." },
        { "ctrlprint", "Prints the saved values of MIDI controllers." },
        { "ctrlprintpresets", "Prints the current collection of presets for MIDI controllers." },
        { "ctrlsave", "Recovers the current values of MIDI controllers." },
        { "ctrlselect", "Loads a preset of values for MIDI controllers." },
        { "cuserrnd", "Continuous user-defined-distribution random number generator." },
        { "dam", "A dynamic compressor/expander." },
        { "date", "Returns the number of seconds since a base date." },
        { "dates", "Returns, as a string, the date and time specified." },
        { "db", "Returns the amplitude equivalent for a given decibel amount." },
        { "dbamp", "Returns the decibel equivalent of a raw amplitude value." },
        { "dbfsamp", "Returns the decibel equivalent of a raw amplitude value, relative to full scale amplitude." },
        { "dcblock", "A DC blocking filter." },
        { "dcblock2", "A DC blocking filter." },
        { "dconv", "A direct convolution opcode." },
        { "dct", "Discrete Cosine Transform of a sample array (type-II DCT)." },
        { "dctinv", "Inverse Discrete Cosine Transform of a sample array (type-III DCT)." },
        { "deinterleave", "Deinterleaves arrays by picking alternate data from its input." },
        { "delay1", "Delays an input signal by one sample." },
        { "delayk", "Delays a k-rate signal by some time interval." },
        { "delayr", "Reads from an automatically established digital delay line." },
        { "delayw", "Writes an audio signal to a digital delay line." },
        { "deltap", "Taps a delay line at variable offset times." },
        { "deltap3", "Taps a delay line at variable offset times, using cubic interpolation." },
        { "deltapi", "Taps a delay line at variable offset times, using interpolation." },
        { "deltapn", "Taps a delay line at variable offset times." },
        { "deltapx", "Reads from or writes to a delay line with interpolation." },
        { "deltapxw", "Mixes the input signal into a delay line." },
        { "denorm", "Mixes low level noise into a list of a-rate signals." },
        { "diff", "Modifies a signal by differentiation." },
        { "diode_ladder", "Zero-delay feedback implementation of a 4-pole diode ladder filter." },
        { "directory", "Reads a directory and outputs a string array of file names." },
        { "diskgrain", "Synchronous granular synthesis, using a soundfile as source." },
        { "diskin", "Reads audio data from an external device or stream and can alter its pitch." },
        { "diskin2", "Reads audio from a file, altering pitch via interpolation and converting to the orchestra sample rate." },
        { "dispfft", "Displays the Fourier Transform of an audio or control signal." },
        { "display", "Displays an audio or control signal as an amplitude vs. time graph." },
        { "distort", "Distorts an audio signal via waveshaping and optional clipping." },
        { "distort1", "Modified hyperbolic tangent distortion." },
        { "divz", "Safely divides two numbers." },
        { "doppler", "Approximates sound propagation and Doppler shifts, without solving equations." },
        { "dot", "Calculates the dot product of two arrays." },
        { "downsamp", "Modifies a signal by down-sampling." },
        { "dripwater", "Semi-physical model of a water drop." },
        { "dumpk", "Periodically writes an orchestra control-signal value to an external file." },
        { "dumpk2", "Periodically writes two orchestra control-signal values to an external file." },
        { "dumpk3", "Periodically writes three orchestra control-signal values to an external file." },
        { "dumpk4", "Periodically writes four orchestra control-signal values to an external file." },
        { "duserrnd", "Discrete user-defined-distribution random number generator." },
        { "dust", "Random impulses." },
        { "dust2", "Random impulses." },
        { "elapsedcycles", "Reads absolute time in k-rate cycles." },
        { "elapsedtime", "Reads absolute time in seconds." },
        { "else", "Executes a block of code when an \"if...then\" condition is false." },
        { "elseif", "Defines another \"if...then\" condition when the previous one is false." },
        { "endif", "Closes a block of code that begins with an \"if...then\" statement." },
        { "endop", "Marks the end of a user-defined opcode block." },
        { "envlpx", "Applies an envelope consisting of 3 segments." },
        { "envlpxr", "The envlpx opcode with a final release segment." },
        { "ephasor", "Produces a periodic phase signal and a periodic exponential decaying signal." },
        { "eqfil", "Equalizer filter." },
        { "evalstr", "Evaluates a string containing Csound code, returning a value." },
        { "event", "Generates a score event from an instrument." },
        { "event_i", "Generates a score event from an instrument, at init-time." },
        { "eventcycles", "Reads absolute time in k-rate cycles." },
        { "eventtime", "Reads absolute time in seconds." },
        { "exciter", "A non-linear filter system used to excite a signal." },
        { "exitnow", "Exits Csound as fast as possible, with no cleanup." },
        { "exp", "Returns e raised to the x-th power." },
        { "expcurve", "Generates a normalised exponential curve in the range 0-1." },
        { "expon", "Traces an exponential curve between specified points." },
        { "exprand", "Exponential distribution random number generator (positive values only)." },
        { "exprandi", "Exponential distribution random number generator with interpolation." },
        { "expsega", "An exponential segment generator operating at a-rate." },
        { "expsegb", "Traces exponential segments between specified absolute points." },
        { "expsegba", "An exponential segment generator operating at a-rate with absolute times." },
        { "expsegr", "Traces exponential segments between specified points, including a release segment." },
        { "fareylen", "Returns the length of a Farey Sequence." },
        { "fareyleni", "Returns the length of a Farey Sequence." },
        { "ficlose", "Closes a previously opened file." },
        { "filebit", "Returns the number of bits per sample in a sound file." },
        { "filelen", "Returns the length of a sound file." },
        { "filenchnls", "Returns the number of channels in a sound file." },
        { "filepeak", "Returns the peak absolute value of a sound file." },
        { "filescal", "Phase-locked vocoder processing with onset detection and 'tempo-scaling'." },
        { "filesr", "Returns the sample rate of a sound file." },
        { "filevalid", "Checks that a file can be read at initialisation or performance time." },
        { "fillarray", "Generates a vector with initial values." },
        { "fft", "Complex-to-complex Fast Fourier Transform." },
        { "filter2", "Filters using a transposed form-II digital filter lattice with no time-varying control." },
        { "fini", "Reads signals from a file at i-rate." },
        { "fink", "Reads signals from a file at k-rate." },
        { "fiopen", "Opens a file in a specific mode." },
        { "flanger", "A user controlled flanger." },
        { "flashtxt", "Allows text to be displayed from instruments, like sliders." },
        { "fluidAllOut", "Collects audio from every Fluidsynth engine in a performance." },
        { "fluidCCi", "Sends a MIDI controller data message to a fluidsynth engine (init-time)." },
        { "fluidCCk", "Sends a MIDI controller data message to a fluidsynth engine (k-rate)." },
        { "fluidControl", "Sends MIDI note on/off and other messages to a SoundFont preset." },
        { "fluidEngine", "Instantiates a fluidsynth engine." },
        { "fluidInfo", "Retrieves program information from the currently loaded soundfont." },
        { "fluidLoad", "Loads a SoundFont into a fluidEngine, optionally listing its contents." },
        { "fluidNote", "Plays a note on a channel in a fluidsynth engine." },
        { "fluidOut", "Outputs sound from a given fluidEngine." },
        { "fluidProgramSelect", "Assigns a preset from a SoundFont to a channel on a fluidEngine." },
        { "fluidSetInterpMethod", "Sets the interpolation method for a channel in a fluidsynth engine." },
        { "fmanal", "AM/FM analysis from a quadrature signal." },
        { "fmax", "Maximum value function." },
        { "fmb3", "Uses FM synthesis to create a Hammond B3 organ sound." },
        { "fmbell", "Uses FM synthesis to create a tubular bell sound." },
        { "fmin", "Minimum value function." },
        { "fmmetal", "Uses FM synthesis to create a \"heavy metal\" sound." },
        { "fmod", "Computes the floating point remainder of a division." },
        { "fmpercfl", "Uses FM synthesis to create a percussive flute sound." },
        { "fmrhode", "Uses FM synthesis to create a Fender Rhodes electric piano sound." },
        { "fmvoice", "FM singing voice synthesis." },
        { "fmwurlie", "Uses FM synthesis to create a Wurlitzer electric piano sound." },
        { "fof", "Produces sinusoid bursts useful for formant and granular synthesis." },
        { "fof2", "Produces sinusoid bursts with k-rate incremental indexing per burst." },
        { "fofilter", "A formant filter." },
        { "fog", "Audio output is a succession of grains derived from a stored function table." },
        { "fold", "Adds artificial foldover to an audio signal." },
        { "follow", "An envelope follower unit generator." },
        { "follow2", "Another controllable envelope extractor." },
        { "foscil", "A basic frequency modulated oscillator." },
        { "foscili", "A basic FM oscillator with linear interpolation." },
        { "fout", "Outputs a-rate signals to an arbitrary number of channels." },
        { "fouti", "Outputs i-rate signals from an arbitrary number of channels to a file." },
        { "foutir", "Outputs i-rate signals from an arbitrary number of channels to a file." },
        { "foutk", "Outputs k-rate signals from an arbitrary number of channels, raw/headerless." },
        { "fprintks", "Like printks, but prints to a file." },
        { "fprints", "Like prints, but prints to a file." },
        { "frac", "Returns the fractional part of a decimal number." },
        { "fractalnoise", "A fractal noise generator." },
        { "framebuffer", "Reads audio into 1-D k-rate arrays and vice versa, with a specified buffer size." },
        { "freeverb", "Opcode version of Jezar's Freeverb." },
        { "ftaudio", "Writes a previously-allocated table to an audio file." },
        { "ftchnls", "Returns the number of channels in a stored function table." },
        { "ftconv", "Low latency multichannel convolution using a function table as impulse response." },
        { "ftcps", "Returns the base frequency of a stored function table, in Hz." },
        { "ftexists", "Queries whether a given function table exists." },
        { "ftfree", "Deletes a function table." },
        { "ftgenonce", "Generates a function table within an instrument definition, without duplicating data." },
        { "ftgentmp", "Generates a score function table that is deleted at the end of the note." },
        { "ftlen", "Returns the size of a stored function table." },
        { "ftload", "Loads a set of previously-allocated tables from a file." },
        { "ftloadk", "Loads a set of previously-allocated tables from a file (k-rate)." },
        { "ftlptim", "Returns the loop segment start-time of a stored function table." },
        { "ftmorf", "Morphs between multiple function tables as specified in a list." },
        { "ftom", "Converts a frequency value to a MIDI note number." },
        { "ftprint", "Prints the contents of a function table (for debugging)." },
        { "ftsamplebank", "Reads a directory for sound files." },
        { "ftsave", "Saves a set of previously-allocated tables to a file." },
        { "ftsavek", "Saves a set of previously-allocated tables to a file (k-rate)." },
        { "ftset", "Sets multiple elements of a table to a given value." },
        { "ftslice", "Copies a slice from one function table to another, at performance time." },
        { "ftslicei", "Copies a slice from one function table to another, at init-time." },
        { "ftsr", "Returns the sampling rate of a stored function table." },
        { "gain", "Adjusts the amplitude of a signal according to a root-mean-square value." },
        { "gainslider", "A logarithmic gain curve similar to Max/MSP's gainslider~ object." },
        { "gtadsr", "A gated linear attack-decay-sustain envelope with exponential release." },
        { "gtf", "Applies a gammatone filter to an audio signal." },
        { "gauss", "Gaussian distribution random number generator." },
        { "gaussi", "Gaussian distribution random number generator with interpolation." },
        { "gausstrig", "Random impulses around a certain frequency." },
        { "gbuzz", "Output is a set of harmonically related cosine partials." },
        { "genarray", "Generates a vector with an arithmetic sequence." },
        { "genarray_i", "Generates a vector with an arithmetic sequence (init-time)." },
        { "gendy", "Dynamic stochastic waveform synthesis conceived by Iannis Xenakis." },
        { "gendyc", "Dynamic stochastic waveform synthesis using cubic interpolation." },
        { "gendyx", "A variation of the dynamic stochastic approach conceived by Iannis Xenakis." },
        { "getcfg", "Returns Csound settings." },
        { "getcol", "Gets a given column from a 2-dimensional array as a vector." },
        { "getftargs", "Fills a string variable with the arguments used to create a function table." },
        { "getrow", "Gets a given row from a 2-dimensional array as a vector." },
        { "getseed", "Reads the global random seed value." },
        { "gogobel", "Audio output is a tone related to striking a cowbell." },
        { "goto", "Transfers control on every pass." },
        { "grain", "Generates granular synthesis textures." },
        { "grain2", "An easy-to-use granular synthesis texture generator." },
        { "grain3", "Generates granular synthesis textures with more user control." },
        { "granule", "A more complex granular synthesis texture generator." },
        { "guiro", "Semi-physical model of a guiro sound." },
        { "harmon", "Analyzes an audio input and generates harmonizing voices in synchrony." },
        { "harmon2", "Analyzes an audio input and generates harmonizing voices, preserving formants." },
        { "hilbert", "A Hilbert transformer." },
        { "hilbert2", "A Hilbert transformer." },
        { "hrtfearly", "Generates 3D binaural audio with early reflections in a parametric room." },
        { "hrtfmove", "Generates dynamic 3D binaural audio for headphones using magnitude interpolation." },
        { "hrtfmove2", "Generates dynamic 3D binaural audio using a Woodworth spherical head model." },
        { "hrtfreverb", "A binaural, dynamic FDN based diffuse-field reverberator." },
        { "hrtfstat", "Generates static 3D binaural audio for headphones." },
        { "hsboscil", "An oscillator which takes tonality and brightness as arguments." },
        { "hvs1", "One-dimensional Hyper Vectorial Synthesis controlled by externally-updated k-variables." },
        { "hvs2", "Two-dimensional Hyper Vectorial Synthesis controlled by externally-updated k-variables." },
        { "hvs3", "Three-dimensional Hyper Vectorial Synthesis controlled by externally-updated k-variables." },
        { "hypot", "Euclidean distance function." },
        { "i", "Returns an init-type equivalent of a k-rate argument, or directly returns an i-rate argument." },
        { "if", "Branches conditionally at initialization or during performance time." },
        { "fftinv", "Complex-to-complex Inverse Fast Fourier Transform." },
        { "igoto", "Transfers control during the i-time pass." },
        { "ihold", "Creates a held note." },
        { "in", "Reads mono audio data from an external device or stream." },
        { "in32", "Reads a 32-channel audio signal from an external device or stream." },
        { "inh", "Reads six-channel audio data from an external device or stream." },
        { "init", "Puts the value of an i-time expression into a k-, a-rate or t-variable." },
        { "initc14", "Initializes the controllers used to create a 14-bit MIDI value." },
        { "initc21", "Initializes the controllers used to create a 21-bit MIDI value." },
        { "initc7", "Initializes the controller used to create a 7-bit MIDI value." },
        { "inleta", "Receives an a-rate signal into an instrument through a named port." },
        { "inletk", "Receives a k-rate signal into an instrument from a named port." },
        { "inletkid", "Receives a k-rate signal into an instrument from a named port." },
        { "inletf", "Receives an f-rate signal (fsig) into an instrument from a named port." },
        { "inletv", "Receives an a-rate array signal into an instrument through a named port." },
        { "ino", "Reads eight-channel audio data from an external device or stream." },
        { "inq", "Reads quad audio data from an external device or stream." },
        { "inrg", "Allows input from a range of adjacent audio channels from the input device." },
        { "ins", "Reads stereo audio data from an external device or stream." },
        { "instr", "Starts an instrument block." },
        { "int", "Extracts the integer part of a decimal number." },
        { "integ", "Modifies a signal by integration." },
        { "interleave", "Interleaves arrays into a single one, placing data in alternating positions." },
        { "interp", "Converts a control signal to an audio signal using linear interpolation." },
        { "invalue", "Reads a k-rate signal from a user-defined channel." },
        { "inx", "Reads a 16-channel audio signal from an external device or stream." },
        { "inz", "Reads multi-channel audio into a ZAK array from an external device or stream." },
        { "jitter", "Generates a segmented line whose segments are randomly generated." },
        { "jitter2", "Generates a segmented line with user-controllable random segments." },
        { "joystick", "Reads data from a joystick controller." },
        { "jspline", "A jitter-spline generator." },
        { "k", "Converts an i-rate parameter to k-rate, or down-samples an a-rate signal to k-rate." },
        { "K35_hpf", "Zero-delay feedback implementation of a Korg35 resonant high-pass filter." },
        { "K35_lpf", "Zero-delay feedback implementation of a Korg35 resonant low-pass filter." },
        { "kgoto", "Transfers control during the performance-time passes." },
        { "kr", "Sets the control rate." },
        { "ksmps", "Sets the number of samples in a control period." },
        { "lag", "Exponential lag." },
        { "lagud", "Exponential lag with separate up/down rates." },
        { "lastcycle", "Indicates whether an event is in its last performance cycle." },
        { "lenarray", "Evaluates the size (or shape length) of an array." },
        { "lfo", "A low frequency oscillator of various shapes." },
        { "lfsr", "A Linear Feedback Shift Register." },
        { "limit", "Sets the lower and upper limits of the value it processes." },
        { "limit1", "A limiting function." },
        { "linenr", "The linen opcode extended with a final release segment." },
        { "lineto", "Generates glissandos starting from a control signal." },
        { "linlin", "Linear to linear interpolation." },
        { "lincos", "Linear to cosine interpolation." },
        { "linrand", "Linear distribution random number generator (positive values only)." },
        { "linsegb", "Traces line segments between specified absolute points." },
        { "linsegr", "Traces line segments between specified points, including a release segment." },
        { "liveconv", "Partitioned convolution with a dynamically reloadable impulse response." },
        { "locsend", "Distributes the audio signals produced by a previous locsig opcode." },
        { "locsig", "Takes an input signal and distributes it between 2 or 4 channels." },
        { "log", "Returns the natural log of a number or array (optional arbitrary base)." },
        { "log10", "Returns a base-10 logarithm." },
        { "log2", "Returns a base-2 logarithm." },
        { "logbtwo", "Performs a base-two logarithmic calculation." },
        { "logcurve", "Generates a normalised logarithmic curve in the range 0-1." },
        { "loop_ge", "A looping construct (continues while greater-or-equal)." },
        { "loop_gt", "A looping construct (continues while greater-than)." },
        { "loop_le", "A looping construct (continues while less-or-equal)." },
        { "loop_lt", "A looping construct (continues while less-than)." },
    };

    inline const char* find (const juce::String& opcodeName)
    {
        const auto trimmed = opcodeName.trim();

        if (trimmed.isEmpty())
            return nullptr;

        for (auto& entry : table)
            if (trimmed.equalsIgnoreCase (entry.name))
                return entry.purpose;

        return nullptr;
    }
}
